# One Dimensional array

In [1]:
import numpy as np

In [2]:
# create row vector

vector_row = np.array([1,2,3])
vector_row

array([1, 2, 3])

In [3]:
# create column vector

vector_col = np.array([[1],
                       [2],
                       [3],
                       [4]])
vector_col

array([[1],
       [2],
       [3],
       [4]])

# Two dimensional array

In [4]:
# create matrix using numpy matrix

matrix = np.matrix([[1,2,3,4],
                    [5,6,7,8]])
matrix

matrix([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [5]:
# create matrix using array (default)
matrix = np.array([[1,2,3,4],
                   [5,6,7,8]])
matrix

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# Sparse Matrix

In [6]:
from scipy import sparse

In [7]:
matrix = np.array([[1,4],
                  [3,0],
                  [0,2]])
matrix

array([[1, 4],
       [3, 0],
       [0, 2]])

In [8]:
#create compressed sparse row
sparse_matrix = sparse.csr_matrix(matrix)
print(sparse_matrix)

  (0, 0)	1
  (0, 1)	4
  (1, 0)	3
  (2, 1)	2


In [9]:
# large matrix
matrix = np.array([[1,4,0,0,0,0,0,0,0,0,0,0],
                   [3,0,0,0,0,0,0,0,0,0,0,0],
                   [0,2,0,0,0,0,0,0,0,0,0,0]])
sparse_matrix = sparse.csr_matrix(matrix)
print(sparse_matrix)

  (0, 0)	1
  (0, 1)	4
  (1, 0)	3
  (2, 1)	2


# Selecting elements from vector and matrix

In [10]:
# select element from vector

vector = np.array([1,2,3,4])
matrix = np.array([[1,2,3,4],
                   [3,4,5,7],
                   [7,8,3,5]])

# select third element from vector
print(vector[2])

# select second row third column from matrix
print(matrix[1,2])

3
5


In [11]:
# select all elements of vector
vector[:]

array([1, 2, 3, 4])

In [12]:
# select all upto 3 elements
vector[:3]

array([1, 2, 3])

In [13]:
# select everything after 3rd element
vector[3:]

array([4])

In [14]:
#select last element
vector[-1]

4

In [15]:
# select frst two rows and all columns of matrix
matrix[:2,:]

array([[1, 2, 3, 4],
       [3, 4, 5, 7]])

In [16]:
# select all rows and 2nd column
matrix[:,1:2]

array([[2],
       [4],
       [8]])

# Describing matrix

In [17]:
# shape, size, dimension

# view number of rows and columns
matrix.shape

(3, 4)

In [18]:
# view number of elements in matrix
matrix.size

12

In [19]:
# view number of dimensions
matrix.ndim

2

# Apply operations to elements

In [20]:
# create matrix
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

# create function that add 100 
add_100 = lambda i : i + 100

# create vectorized funciton
vectorized_add_100 = np.vectorize(add_100)

# apply function to all elements
vectorized_add_100(matrix)



array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [21]:
# Add 100 to all elements
matrix + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

# Min and Max Value of matrix

In [22]:
# return minimum element
np.min(matrix)

1

In [23]:
# return maximum element
np.max(matrix)

9

In [24]:
# min element in each column
np.min(matrix, axis=0)

array([1, 2, 3])

In [25]:
# min element in each row
np.min(matrix, axis=1)

array([1, 4, 7])

In [26]:
# max element in each column
np.max(matrix, axis=0)

array([7, 8, 9])

In [27]:
# max element in each row
np.max(matrix, axis=1)

array([3, 6, 9])

# calculate average, variance, standard deviation

In [28]:
# mean
np.mean(matrix)

5.0

In [29]:
# variance
np.var(matrix)

6.666666666666667

In [30]:
# standard deviation
np.std(matrix)

2.581988897471611

In [31]:
# mean in each column
np.mean(matrix, axis=0)

array([4., 5., 6.])

# Reshaping arrays

In [32]:
# create 4 x 3 matrix
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9],
                   [10,11,12]])

# reshape matrix into 2 x 6 matrix
matrix.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [33]:
# reshape -1 as many as needed

matrix.reshape(-1,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [34]:
# reshape 1D array
matrix.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Transpose vector or matrix

In [35]:
# create matrix
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

# transpose of matrix
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [36]:
# transpose a row vector to column vector
vector = np.array([[1,2,3,4,5,6]])

vector.T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

# Flattening a matrix

In [37]:
# create matrix 
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

# flatten a matrix
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
# alternatively use reshape -1
matrix.reshape(1,-1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

# Rank of Matrix

In [39]:
np.linalg.matrix_rank(matrix)

2

# Determinant of matrix

In [40]:
np.linalg.det(matrix)

0.0

# Diagonal of matrix

In [41]:
# return main diagonal
matrix.diagonal()

array([1, 5, 9])

In [42]:
# return one diagonal above main diagonal
matrix.diagonal(offset=1)

array([2, 6])

In [43]:
# return one diagonal below main diagonal
matrix.diagonal(offset=-1)

array([4, 8])

# Trace of matrix

sum of the diagonal elements

In [44]:
#create a matrix
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
matrix.trace()

15

In [45]:
# alternatively use sum with diagonal
sum(matrix.diagonal())

15

# Eigenvalues and Eigenvectors
eigenvectors are vectors that, when that
transformation is applied, change only in scale (not direction).

In [46]:
# create matrix
matrix = np.array([[1,-1,3],
                   [1,1,6],
                   [3,8,9]])

# calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

# view eigenvalues
eigenvalues

array([13.55075847,  0.74003145, -3.29078992])

In [47]:
# view eigenvectors
eigenvectors

array([[-0.17622017, -0.96677403, -0.53373322],
       [-0.435951  ,  0.2053623 , -0.64324848],
       [-0.88254925,  0.15223105,  0.54896288]])

# Dot Product

In [48]:
# create two vectors
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])

# calculate dot product
np.dot(vector_a, vector_b)

32

In [49]:
# alternatively use @

vector_a @ vector_b

32

# Adding and Subtracting Matrices


In [50]:
# create two matrices

matrix_a = np.array([[1,2,3],
                    [4,5,6],
                     [7,8,9]])
matrix_b = np.array([[1,1,1],
                    [1,1,1],
                     [1,1,1]])
# add two matrices
np.add(matrix_a, matrix_b)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [51]:
# alternatively use +
matrix_a + matrix_b

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [52]:
# subtract two matrices
np.subtract(matrix_a, matrix_b)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [53]:
# Alternatively use -
matrix_a - matrix_b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Multiplying matrices

In [54]:
# create two matrices
matrix_a = np.array([[1,1],
                     [1,3]])
matrix_b = np.array([[1,3],
                     [1,2]])

# multiply two matrices
np.dot(matrix_a, matrix_b)

array([[2, 5],
       [4, 9]])

In [55]:
# alternatively use @
matrix_a @ matrix_b

array([[2, 5],
       [4, 9]])

In [56]:
# elementwise multiplication, use *
matrix_a * matrix_b

array([[1, 3],
       [1, 6]])

# Inverse of matrix

In [57]:
# create matrix
matrix = np.array([[4,3],
                   [3,2]])

# calculate inverse of matrix
np.linalg.inv(matrix)

array([[-2.,  3.],
       [ 3., -4.]])

In [58]:
# multiply matrix with its inverse
matrix @ np.linalg.inv(matrix)

array([[1., 0.],
       [0., 1.]])

# Generate Random Values

In [59]:
# set seed
np.random.seed(0)

# generate three random floats between 0.0 and 1.0
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])

In [60]:
#generate 4 random numbers between 1 and 10
np.random.randint(0,11,4)

array([3, 7, 9, 3])

In [61]:
# draw three numbers from a normal distribution with mean 0.0 and standard deviation of 1.0
np.random.normal(0,1,3)

array([-0.84272405,  1.96992445,  1.26611853])

In [62]:
# draw three numbers from a logistic distribution with mean 0.0 and scale of 1.0
np.random.logistic(0,1,3)

array([0.1157086 , 0.27387744, 2.52093742])

In [63]:
# draw three numbers greater than or equal to 1.0 and less than 2.0
np.random.uniform(1.0,2.0,3)

array([1.07103606, 1.0871293 , 1.0202184 ])